spring:
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
  datasource:
    url: jdbc:postgresql://localhost:32768/shop
    username: admin
    password: 281998
  flyway:
    baseline-on-migrate: true

